import type { DecisionTrace } from '../api/research';
import type { FreshnessStatus } from '../api/freshness';

const labels: Record<FreshnessStatus, string> = { UNKNOWN: 'Unknown chain time', FUTURE: 'Future chain time', STALE: 'Older than policy', WITHIN_POLICY: 'Within recorded policy' };
export function ChainFreshnessEvidence({ trace }: { trace: DecisionTrace }) {
  const report = trace.chain_freshness;
  return <section className="freshness-evidence space-top" aria-labelledby="chain-freshness-title"><div className="sectionhead"><div><p className="eyebrow">Historical input quality</p><h3 id="chain-freshness-title">Captured chain age</h3></div><span className={'pill ' + (report?.status === 'WITHIN_POLICY' ? 'blue' : 'amber')}>{report ? labels[report.status] : 'Unmeasured legacy record'}</span></div>
    <p className="muted space-top">Age at this recorded evaluation. This observation does not measure current provider or service health.</p>
    {!report ? <p className="notice">No chain freshness report was retained. Chain age and the applicable age limit are unknown. Capture / evaluation elapsed time alone cannot establish chain age.</p> : <>
      <dl className="research-facts"><dt>Observation reference</dt><dd>{new Date(report.reference_observed_at_unix_ms).toISOString()}</dd><dt>Evaluation elapsed</dt><dd>{report.evaluation_elapsed_ms} ms</dd><dt>Declared maximum chain age</dt><dd>{report.policy.max_chain_age_ms} ms</dd><dt>Policy</dt><dd>{report.policy.version}</dd></dl>
      <p className="tiny">For a known timestamp, chain age equals observation reference plus evaluation elapsed minus chain timestamp. Base uses a finalized block timestamp; Solana block time is an estimate.</p>
      {!report.sources.length && <p className="notice">No capture sources were retained. Chain age is unknown.</p>}
      <div className="freshness-sources space-top">{report.sources.map((source, i) => <article className="freshness-source" key={source.capture_id}><div className="sectionhead"><h4>Capture {i + 1}</h4><span className={'pill ' + (source.status === 'WITHIN_POLICY' ? 'blue' : 'amber')}>{labels[source.status]}</span></div><p className="tiny mono space-top">{source.capture_id}</p><dl className="research-facts"><dt>Source</dt><dd>{source.source.kind === 'BASE_FINALIZED_BLOCK_TIMESTAMP' ? 'Base finalized block timestamp' : 'Solana estimated block time'}</dd><dt>{source.source.kind === 'BASE_FINALIZED_BLOCK_TIMESTAMP' ? 'Block number' : 'Finalized slot'}</dt><dd>{source.source.kind === 'BASE_FINALIZED_BLOCK_TIMESTAMP' ? source.source.block_number : source.source.slot}</dd><dt>Chain timestamp</dt><dd>{source.chain_time_seconds === null ? 'Unknown — timestamp unavailable' : new Date(source.chain_time_seconds * 1000).toISOString()}</dd><dt>Captured chain age</dt><dd>{source.age_ms === null ? source.status === 'FUTURE' ? 'Unavailable — timestamp is in the future' : 'Unknown' : source.age_ms + ' ms'}</dd></dl>{source.status === 'STALE' && <p className="notice">The captured chain age exceeded the declared maximum at evaluation.</p>}{source.status === 'FUTURE' && <p className="notice">The source timestamp was later than the evaluation reference. No zero age was substituted.</p>}{source.status === 'UNKNOWN' && <p className="notice">The source supplied no usable chain time. Freshness remains unknown.</p>}</article>)}</div>
      <p className="notice">Passing this age policy does not qualify provider correctness, account coherence, protocol equivalence, costs or transaction execution. Dataset origin remains {trace.dataset_origin.replaceAll('_', ' ')}.</p>
    </>}
  </section>;
}
