import { useState } from 'react';
import type { Capabilities, ControlApi, Network, Session } from '../api/client';
import type { Origin, StoredDecision } from '../api/research';
import { useResearchPagination, useResearchResource } from '../hooks/useResearchResource';
import { EmptyResearch, Exact, ExportButton, OriginBadge, Pagination, ResearchDialog, ResourceStatus } from './ResearchShared';
import { FrozenSessionExport } from './FrozenSessionExport';

interface Props { active: boolean; api: ControlApi; capabilities: Capabilities; sessions: Session[]; filter: Network | 'all' }
const origins: Origin[] = ['RECORDED_LIVE', 'SYNTHETIC', 'MANUALLY_CONSTRUCTED'];
export function DecisionExplorer({ active, api, capabilities, sessions, filter }: Props) {
  const [sessionId, setSessionId] = useState(''), [origin, setOrigin] = useState<Origin | 'all'>('all');
  const [observationId, setObservationId] = useState('');
  const selected = sessions.find(session => session.session_id === sessionId);
  const available = capabilities.decision_history === true;
  const enabled = active && available && Boolean(selected);
  const pages = useResearchPagination(sessionId), groupsPage = useResearchPagination(sessionId);
  const observations = useResearchResource(enabled, 'observations:' + sessionId + ':' + (pages.cursor ?? ''), signal => api.decisions(sessionId, pages.cursor, signal));
  const coverage = useResearchResource(enabled, 'coverage:' + sessionId, signal => api.coverage(sessionId, signal));
  const groups = useResearchResource(enabled, 'groups:' + sessionId + ':' + (groupsPage.cursor ?? ''), signal => api.decisionGroups(sessionId, groupsPage.cursor, signal));
  const detail = useResearchResource(enabled && Boolean(observationId), 'decision:' + sessionId + ':' + observationId, async signal => {
    const value = await api.decision(observationId, signal);
    if (value.trace.session_id !== sessionId) throw new Error('The trace belongs to a different session.');
    return value;
  });
  const rows = observations.data?.items.filter(item => origin === 'all' || item.trace.dataset_origin === origin) ?? [];
  const options = sessions.filter(session => filter === 'all' || session.network_id === filter || session.session_id === sessionId);
  function refresh() { observations.refresh(); coverage.refresh(); groups.refresh(); if (observationId) detail.refresh(); }
  return <section className="section-spacer research-workspace" aria-labelledby="decision-explorer-title">
    <div className="sectionhead"><div><h2 id="decision-explorer-title">Decision evidence explorer</h2><p>Persisted observations, grouped candidates and rejection evidence. Quotes alone do not establish arbitrage profit.</p></div><span className="pill blue">PERSISTED EVIDENCE</span></div>
    {!available ? <EmptyResearch>Decision history is unavailable in this API version. Missing observations and execution accounting are unknown, not zero.</EmptyResearch> : <>
      <div className="panel research-toolbar"><div className="research-field"><label htmlFor="decision-session">Decision session</label><select id="decision-session" value={sessionId} onChange={event => { setSessionId(event.target.value); setObservationId(''); setOrigin('all'); }}><option value="">Choose a session</option>{options.map(session => <option key={session.session_id} value={session.session_id}>{session.session_id} · {session.network_id} · {session.mode}</option>)}</select></div><div className="research-field"><label htmlFor="decision-origin">Origin on this page</label><select id="decision-origin" value={origin} onChange={event => setOrigin(event.target.value as Origin | 'all')}><option value="all">All recorded origins</option>{origins.map(value => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></div><button disabled={!enabled || observations.loading || coverage.loading || groups.loading} onClick={refresh}>Refresh evidence</button></div>
      {!selected ? <EmptyResearch>Select a session to inspect its stored evidence. No dataset has been substituted.</EmptyResearch> : <>
        <p className="tiny space-top">Session scope: {sessionId}. The chain selector filters session choices only; changing it does not change this selected evidence scope. Origin filtering affects the observation page below. Aggregate counts include all origins in this session. Counts and pages are separate received snapshots and can differ while recording continues.</p>
        <FrozenSessionExport key={sessionId} api={api} sessionId={sessionId} active={enabled} available={capabilities.session_export === true} />
        <ResourceStatus resource={coverage} />
        {coverage.data && <section className="panel space-top" aria-label="Session evidence counts"><h3>Stored observation counts · all origins</h3><div className="research-metrics">
          {[['Raw observations', coverage.data.raw_observations], ['Quoted candidates', coverage.data.quoted_candidates], ['Unique quoted groups', coverage.data.unique_opportunity_groups], ['Rejected', coverage.data.rejected], ['No route', coverage.data.no_route], ['Data unavailable', coverage.data.data_unavailable], ['Eligible attempts', coverage.data.eligible_attempts], ['Reconciled transactions', coverage.data.reconciled_transactions]].map(([label, value]) => <div className="fact" key={label}><span className="metriclabel">{label}</span><strong><Exact value={value} /></strong></div>)}
        </div><p className="notice">Collection completeness: UNKNOWN. Stored observations are not a census of market activity. Unique quoted groups include negative gross quotes; they are not counts of profitable trades.</p><p className="tiny">Stored observation window: {coverage.data.coverage_window_start_ms === null ? 'Unknown' : new Date(coverage.data.coverage_window_start_ms).toISOString()} → {coverage.data.coverage_window_end_ms === null ? 'Unknown' : new Date(coverage.data.coverage_window_end_ms).toISOString()}. This range does not establish uninterrupted collection.</p></section>}
        <div className="sectionhead space-top"><div><h3>Raw decision observations</h3><p>{rows.length} shown on this loaded page. External costs and full transaction simulation remain outside this gross quote evidence.</p></div><ExportButton label="Export observation page JSON" scope={'observation-page-' + sessionId + '-origin-' + origin} data={observations.data ? { items: rows, next_cursor: observations.data.next_cursor } : null} receivedAt={observations.at} /></div>
        <ResourceStatus resource={observations} />
        {observations.data && !rows.length && <EmptyResearch>No matching observations on this page. Other pages and uncollected market activity remain separate.</EmptyResearch>}
        {rows.length > 0 && <div className="research-scroll"><table className="research-table"><caption>Stored decision observations · exact start asset minor units</caption><thead><tr><th>Observation / origin</th><th>Result / reasons</th><th>Gross delta</th><th>Evidence</th></tr></thead><tbody>{rows.map(item => <tr key={item.trace_id}><td><strong className="mono">{item.trace.observation_id}</strong><span className="route-sub">{item.trace.network_id} · {item.trace.mode}</span><OriginBadge origin={item.trace.dataset_origin} /></td><td><span className="pill">{item.trace.result.status === 'QUOTED' ? 'CANDIDATE · GROSS QUOTE' : item.trace.result.status.replaceAll('_', ' ')}</span><span className="route-sub">{item.trace.result.status === 'QUOTED' ? 'Net unknown — external costs incomplete' : item.trace.result.reason_codes.join(' · ') || 'No reason supplied'}</span></td><td><Exact value={item.trace.result.status === 'QUOTED' ? item.trace.result.gross_delta_minor : null} /><span className="route-sub">{item.trace.route[0]?.asset_in ?? 'Start asset unavailable'}</span></td><td><button onClick={() => setObservationId(item.trace.observation_id)} aria-label={'Inspect decision ' + item.trace.observation_id}>Inspect evidence</button></td></tr>)}</tbody></table></div>}
        <Pagination label="observations" page={pages.page} canPrevious={pages.canPrevious} canNext={pages.canNext(observations.data?.next_cursor)} loading={observations.loading} previous={pages.previous} next={() => { if (observations.data?.next_cursor) pages.next(observations.data.next_cursor); }} />
        <div className="sectionhead space-top"><div><h3>Grouped observation windows · all origins</h3><p>Grouping separates dataset origin, network and configuration. This page includes rejected and unavailable observation groups.</p></div></div><ResourceStatus resource={groups} />
        {groups.data && !groups.data.items.length && <EmptyResearch>No grouped observations were returned for this page.</EmptyResearch>}
        {groups.data && groups.data.items.length > 0 && <div className="research-scroll"><table className="research-table"><caption>Grouping evidence by stored window</caption><thead><tr><th>Group / origin</th><th>Raw</th><th>Quoted</th><th>Rejected</th><th>No route</th><th>Unavailable</th></tr></thead><tbody>{groups.data.items.map(group => <tr key={group.grouping_version + ':' + group.grouping_key + ':' + group.window_start_ms}><td><span className="mono">{group.grouping_key}</span><span className="route-sub">{group.grouping_version} · {new Date(group.window_start_ms).toISOString()}</span><OriginBadge origin={group.dataset_origin} /></td><td><Exact value={group.raw_observations} /></td><td><Exact value={group.quoted_candidates} /></td><td><Exact value={group.rejected} /></td><td><Exact value={group.no_route} /></td><td><Exact value={group.data_unavailable} /></td></tr>)}</tbody></table></div>}
        <Pagination label="groups" page={groupsPage.page} canPrevious={groupsPage.canPrevious} canNext={groupsPage.canNext(groups.data?.next_cursor)} loading={groups.loading} previous={groupsPage.previous} next={() => { if (groups.data?.next_cursor) groupsPage.next(groups.data.next_cursor); }} />
      </>}
    </>}
    <ResearchDialog open={active && Boolean(observationId)} title="Decision evidence detail" close={() => setObservationId('')}>
      <ResourceStatus resource={detail} />{detail.data && <DecisionDetail record={detail.data} receivedAt={detail.at} />}<button className="space-top" disabled={detail.loading} onClick={detail.refresh}>Refresh selected trace</button>
    </ResearchDialog>
  </section>;
}
function DecisionDetail({ record, receivedAt }: { record: StoredDecision; receivedAt: number | null }) {
  const trace = record.trace;
  return <div className="research-detail"><div className="research-actions"><OriginBadge origin={trace.dataset_origin} /><span className="pill">{trace.result.status === 'QUOTED' ? 'CANDIDATE · GROSS QUOTE' : trace.result.status.replaceAll('_', ' ')}</span></div><dl className="research-facts">
    <dt>Observation</dt><dd>{trace.observation_id}</dd><dt>Durable trace</dt><dd>{record.trace_id}</dd><dt>Stored at</dt><dd>{record.recorded_at}</dd><dt>Observed at</dt><dd>{new Date(trace.observed_at_unix_ms).toISOString()}</dd><dt>Capture / evaluation elapsed time</dt><dd><span className="research-exact">{trace.input_age_ms === null ? 'Unknown' : trace.input_age_ms + ' ms'}</span><p className="tiny">Elapsed batch time; current chain-state age is unqualified.</p></dd><dt>Session / experiment</dt><dd>{trace.session_id} / {trace.experiment_id}</dd><dt>Network / mode</dt><dd>{trace.network_id} / {trace.mode}</dd><dt>Source kind</dt><dd>{trace.source_kind}</dd><dt>Frozen configuration</dt><dd>{trace.configuration_digest}</dd><dt>Calculation / generation</dt><dd>{trace.calculation_version} / {trace.generation}</dd><dt>Strategy</dt><dd>{trace.strategy_id}</dd><dt>Start asset</dt><dd>{trace.route[0]?.asset_in ?? 'Unavailable'}</dd><dt>Input · minor units</dt><dd><Exact value={trace.amount_in_minor} /></dd>
    {trace.result.status === 'QUOTED' && <><dt>Quoted output · minor units</dt><dd><Exact value={trace.result.quoted_output_minor} /></dd><dt>Gross delta · minor units</dt><dd><Exact value={trace.result.gross_delta_minor} /></dd><dt>Pool fees included in quote</dt><dd>{trace.result.included_pool_fees.length ? trace.result.included_pool_fees.map((fee, index) => <p key={index}>{fee} minor units · {trace.route[index]?.asset_in ?? 'Asset unavailable'}</p>) : 'No fee evidence supplied'}</dd></>}
    <dt>Net after external costs</dt><dd>Unknown — external costs incomplete</dd><dt>Capture artifact retention</dt><dd>Unknown — references do not prove raw artifacts remain available</dd>
  </dl><h3>Route and calculation inputs</h3>{trace.route.length ? trace.route.map((leg, i) => <div className="notice" key={i}><p>{leg.venue_family} · {leg.pool_id}</p><p>{leg.asset_in} → {leg.asset_out}</p></div>) : <p className="notice">No route was supplied for this result.</p>}
  <h3 className="space-top">Capture references</h3>{trace.capture_refs.length ? trace.capture_refs.map((ref, i) => <dl className="research-facts" key={i}><dt>Capture</dt><dd>{ref.capture_id}</dd><dt>Manifest digest</dt><dd>{ref.manifest_digest}</dd><dt>Snapshot</dt><dd>{ref.snapshot_id}</dd></dl>) : <p className="notice">No capture references supplied. Dataset origin remains {trace.dataset_origin}.</p>}
  <div className="notice"><p>Grouping: {trace.grouping.version} · {trace.grouping.key} · {trace.grouping.window_ms} ms window.</p><p>Reasons: {trace.result.status === 'QUOTED' ? 'Quoted candidate; external costs and simulation are not established.' : trace.result.reason_codes.join(' · ') || 'None supplied'}</p><p>Diagnostics: {trace.diagnostics.join(' · ') || 'None supplied'}</p><p>This evidence does not establish an executable or realized trading result.</p></div>
  <ExportButton label="Export selected trace JSON" scope={'decision-' + trace.observation_id} data={record} receivedAt={receivedAt} /></div>;
}
