import { useEffect, useRef } from 'react';
import type { KeyboardEvent } from 'react';
import type { Opportunity } from '../api/client';
const names = { 'base-mainnet': 'Base', 'solana-mainnet': 'Solana' };
function evidenceText(row: Opportunity) { return row.simulation_status === 'FAILED' ? 'REJECTED · simulation failed' : row.evidence_label.replaceAll('_', ' '); }
export function RecordedTable({ rows, inspect }: { rows: Opportunity[]; inspect: (row: Opportunity) => void }) {
  return <div className="tablewrap space-top"><table><caption className="sr">Captured market observations. Amounts remain exact integer minor units of the named start asset.</caption><thead><tr><th>Route / chain</th><th>Evidence</th><th className="num">Input · minor units</th><th className="num">Net · minor units</th><th>Quality / provenance</th><th><span className="sr">Details</span></th></tr></thead><tbody>{rows.map(row => <tr key={row.opportunity_id}><td><span className="route">{row.route.map(leg => leg.venue_family).join(' → ')}</span><span className="route-sub">{names[row.network_id]} · {row.opportunity_id}</span></td><td><span className={`pill ${row.simulation_status === 'FAILED' ? 'amber' : 'blue'}`}>{evidenceText(row)}</span></td><td className="num">{row.amount_in_minor}</td><td className="num"><span className="mobilelabel">Net · start asset minor units</span>{row.eligibility_checks.costs_complete ? row.net_after_explicit_costs_minor : 'Unknown — costs incomplete'}<span className="route-sub">{row.start_asset_id}</span></td><td><span className="route-sub">{row.snapshot.complete && row.snapshot.consistent ? 'Coherent snapshot' : 'Incomplete / inconsistent'}</span><span className="route-sub">{row.eligibility_checks.state_fresh_and_coherent ? 'Fresh at evaluation' : 'Stale / ineligible at evaluation'}</span><span className="route-sub">Observed {row.observed_at}</span></td><td><button className="cellbtn" onClick={() => inspect(row)} aria-label={`Inspect ${row.opportunity_id}`}>Inspect</button></td></tr>)}</tbody></table><div className="tablefoot">Raw minor units preserve precision. Start-asset decimals are not supplied by this API. Paper results remain hypothetical.</div></div>;
}
export function RecordedDialog({ opportunity: row, onClose }: { opportunity: Opportunity | null; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const close = useRef<HTMLButtonElement>(null);
  useEffect(() => {
    const node = dialog.current; if (!node || !row) return;
    const previous = document.activeElement; node.showModal(); close.current?.focus();
    return () => { node.close(); if (previous instanceof HTMLElement && previous.isConnected) previous.focus(); };
  }, [row]);
  function trap(event: KeyboardEvent<HTMLDialogElement>) { if (event.key === 'Tab' && !event.ctrlKey && !event.altKey && !event.metaKey) { event.preventDefault(); close.current?.focus(); } }
  return <dialog ref={dialog} aria-labelledby="record-title" onKeyDown={trap} onCancel={event => { event.preventDefault(); onClose(); }}>{row && <><div className="dialoghead"><div><p className="eyebrow">Captured market record</p><h2 id="record-title">{row.opportunity_id}</h2></div><button ref={close} onClick={onClose}>Close record detail</button></div><span className="pill blue">{evidenceText(row)}</span><p className="space-top">{row.mode} · {names[row.network_id]} · {row.start_asset_id}</p><table className="detailcosts"><caption className="sr">Exact start-asset amounts and provenance</caption><tbody><tr><th>Input · minor units</th><td>{row.amount_in_minor}</td></tr><tr><th>Quoted output · minor units</th><td>{row.quoted_output_minor}</td></tr><tr><th>Net after explicit costs · minor units</th><td>{row.eligibility_checks.costs_complete ? row.net_after_explicit_costs_minor : 'Unknown: costs incomplete'}</td></tr>{row.costs.map((cost, index) => <tr key={`${cost.kind}-${index}`}><th>{cost.kind}<span className="route-sub">Valuation: {cost.valuation_reference}</span></th><td>{cost.in_start_asset_minor}<span className="route-sub">Native {cost.native_amount.amount_minor} minor units · {cost.native_amount.asset_id}</span></td></tr>)}</tbody></table>{!row.costs.length && <p className="notice">No explicit cost rows supplied. Missing cost evidence must not be interpreted as a zero network fee.</p>}<div className="notice"><strong>Provenance</strong><p>Observed: {row.observed_at}</p><p>State: {row.snapshot.state_reference}</p><p>Snapshot: {row.snapshot.snapshot_id}</p><p>Provider: {row.snapshot.source}</p><p>Age at evaluation: {row.snapshot.age_ms} ms · {row.snapshot.finality_label}</p><p>Finality: {row.finality_status}</p><p>Plan: {row.execution_plan_digest ?? 'No execution plan supplied'}</p><p>Scenario: {row.inclusion_scenario_id ?? 'No inclusion scenario supplied'}</p></div><div className="space-top"><h3>Route and eligibility</h3>{row.route.map((leg, i) => <p className="tiny space-top" key={i}>{leg.asset_in} → {leg.asset_out} · {leg.venue_family} · {leg.pool_id}</p>)}{Object.entries(row.eligibility_checks).map(([key, value]) => <p className="tiny" key={key}>{key.replaceAll('_', ' ')}: {value ? 'Pass' : 'Not satisfied'}</p>)}</div><div className="notice">{row.reason_codes.length ? row.reason_codes.join(' · ') : 'No rejection reasons supplied.'}<p>Simulation: {row.simulation_status}. {row.evidence_label === 'REALIZED' ? `Transaction: ${row.transaction_id}` : 'This record is not a realized trading result.'}</p></div><p className="tiny space-top">Pool fees and price impact are included in the quoted output. Infrastructure costs and unallocated failures are separate.</p></>}</dialog>;
}
