import type { Chain } from './lifecycle.ts';

export type DemoEvidence = 'Candidate' | 'Simulated' | 'Estimated executable';
export interface Opportunity {
  id: string;
  chain: Chain;
  route: string;
  venue: string;
  evidence: DemoEvidence;
  input: string;
  range: string;
  gross: string;
  costs: string;
  quality: string;
  reason: string;
}

// Fixed fictional illustrations. These are UI fixture labels, never evidence
// generated by a simulator, feed, or execution service.
export const SAMPLE_CAPTURE = '12 Sep 2026, 12:00 UTC';
export const chains = {
  solana: { name: 'Solana', symbol: 'S', venue: 'Orca Whirlpools', asset: 'wSOL', candidates: 48, simulated: 19, eligible: 4, coverage: 98.4, quality: 'Partial · sample reconnect gap', freshness: '120 ms at capture' },
  base: { name: 'Base', symbol: 'B', venue: 'Uniswap V3', asset: 'WETH', candidates: 36, simulated: 12, eligible: 3, coverage: 100, quality: 'Complete sample window', freshness: '180 ms at capture' },
} as const;

export const opportunities: readonly Opportunity[] = [
  {
    id: 'SOL-001', chain: 'solana', route: 'USDC → wSOL → USDC', venue: 'Orca Whirlpools · pools A / B', evidence: 'Estimated executable', input: '1,000 USDC', range: '+0.30 to +1.10', gross: '+1.60', costs: '0.50–1.30', quality: 'Coherent sample state',
    reason: 'Fictional example of complete atomic simulation and all eligibility checks passing under a named baseline delay scenario. Freshness, funding, fees and guards are assumed. Inclusion is not established.',
  },
  {
    id: 'BASE-001', chain: 'base', route: 'USDC → WETH → USDC', venue: 'Uniswap V3 · fee tiers A / B', evidence: 'Simulated', input: '1,000 USDC', range: '−0.40 to +0.20', gross: '+0.80', costs: '0.60–1.20', quality: 'Fee uncertainty',
    reason: 'Fictional successful complete transaction simulation whose cost range crosses zero. Eligibility checks did not all pass. Successful simulation does not imply profit.',
  },
  {
    id: 'SOL-002', chain: 'solana', route: 'USDC → wSOL → USDC', venue: 'Orca Whirlpools · pools C / D', evidence: 'Candidate', input: '500 USDC', range: 'Not evaluated', gross: 'Not evaluated', costs: 'Unknown', quality: 'Quote only',
    reason: 'Fictional quote-only route. No complete atomic transaction simulation exists for this example.',
  },
  {
    id: 'BASE-002', chain: 'base', route: 'USDC → WETH → USDC', venue: 'Uniswap V3 · fee tiers C / D', evidence: 'Candidate', input: '2,000 USDC', range: 'Not evaluated', gross: 'Not evaluated', costs: 'Unknown', quality: 'Stale sample rejected',
    reason: 'Fictional stale state was rejected before simulation. A cached quote cannot be presented as a current executable opportunity.',
  },
  {
    id: 'SOL-003', chain: 'solana', route: 'USDC → wSOL → USDC', venue: 'Orca Whirlpools · pools E / F', evidence: 'Simulated', input: '750 USDC', range: '+0.10 to +0.55', gross: '+0.95', costs: '0.40–0.85', quality: 'Funding check pending',
    reason: 'Fictional complete atomic simulation succeeded. Funding eligibility remains unknown, so this example is not estimated executable.',
  },
  {
    id: 'BASE-003', chain: 'base', route: 'USDC → WETH → USDC', venue: 'Uniswap V3 · fee tiers E / F', evidence: 'Estimated executable', input: '1,500 USDC', range: '+0.20 to +0.70', gross: '+1.30', costs: '0.60–1.10', quality: 'Coherent sample state',
    reason: 'Fictional complete atomic simulation and modeled eligibility pass under the baseline delay scenario. Competitor transactions can still change an outcome.',
  },
];
