[package]
name = "arb-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
arb-domain.workspace = true
arb-config.workspace = true
arb-adapter-api.workspace = true
arb-evm.workspace = true
arb-solana.workspace = true
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[dev-dependencies]
bs58 = "=0.5.1"

[lints]
workspace = true
